baseURL = "https://osterbackaphoto.com"
languageCode = "sv-SE"
title = "Osterbacka Photo"
theme = ""
paginate = 10

[params]
  description = "Jag fotar matcher – och annat jag tycker är kul att fånga med kameran."
  author = "Esko Österbacka"
